#########################################################################################
##  DEPLOY TO AZURE STATIC WEB AOO STAGING ENVIRONMENT
#########################################################################################
name: Azure Static Web Apps CI/CD

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    # Creates output variable to be used in steps or other jobs.
    outputs:
      PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_0E59B2C0F }}
          repo_token: ${{ secrets.GH_API_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/eslutz.github.io" # Built app content directory - optional
          skip_api_build: true # Set to true to skip building the API functions - optional
          ###### End of Repository/Build Configurations ######

      - name: Get Version Number
        id: version
        run: |
          packageVersion="v$(npm pkg get version | sed 's/"//g')"
          echo "package version: $packageVersion"
          echo "PACKAGE_VERSION=$packageVersion" >> $GITHUB_OUTPUT

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Create Release and Close Pull Request Job
    runs-on: ubuntu-latest
    needs: build_and_deploy_job
    env:
      RELEASE_VERSION: ${{ needs.build_and_deploy_job.outputs.PACKAGE_VERSION }}
    steps:
      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_API_TOKEN }}
          script: |
            const {RELEASE_VERSION} = process.env

            try {
              const response = github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `${RELEASE_VERSION}`,
                target_commitish: context.sha,
                name: `Release ${RELEASE_VERSION}`,
                draft: false,
                prerelease: false,
                generate_release_notes: true,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_0E59B2C0F }}
          action: "close"
