#########################################################################################
##  UPDATE PROJECT DEPENDENCIES
#########################################################################################
name: Update Portfolio Site Dependencies

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 */14 * *'

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  update_npm_dependencies:
    runs-on: ubuntu-latest
    name: Update NPM Dependencies Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install & update dependencies
        run: npm run upd-pkg-ver

      - name: Commit & push changes
        run: |
          git config --global user.email "${{ vars.COMMIT_USER_EMAIL }}"
          git config --global user.name "${{ vars.COMMIT_USER_NAME }}"
          git add --update
          git commit -m "updated project dependencies" || exit 0
          git push --force
