#########################################################################################
##  UPDATE PROJECT DEPENDENCIES
#########################################################################################
name: Update Portfolio Site Dependencies

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 */14 * *'

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  update_npm_dependencies:
    runs-on: ubuntu-latest
    name: Update NPM Dependencies Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update package.json to latest versions
        run: ncu -u

      - name: Install updated dependencies
        run: npm install

      - name: Commit & push changes
        run: |
          git config --global user.email "${{ vars.COMMIT_USER_EMAIL }}"
          git config --global user.name "${{ vars.COMMIT_USER_NAME }}"
          git add package.json package-lock.json
          git commit -m "Update dependencies to latest versions" || exit 0
          git push --force
