name: Deploy Portfolio Site Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'iac/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        id: deploy-bicep
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ vars.AZURE_REGION }}
          template: ./iac/main.bicep
          parameters: >-
            location=${{ vars.AZURE_REGION }}
            appName=${{ vars.APP_NAME }}
            repoUrl=${{ github.server_url }}/${{ github.repository }}
            repoBranch=${{ github.ref_name }}
            existingCosmosDbAccountName=${{ vars.COSMOS_ACCOUNT_NAME }}
            existingCosmosDbResourceGroup=${{ vars.COSMOS_RESOURCE_GROUP }}

      - name: Get SWA deployment token
        id: get-swa-token
        run: |
          TOKEN=$(az staticwebapp secrets list \
            --name ${{ steps.deploy-bicep.outputs.staticWebAppName }} \
            --resource-group ${{ steps.deploy-bicep.outputs.resourceGroupName }} \
            --query "properties.apiKey" -o tsv)
          echo "::add-mask::$TOKEN"
          echo "swa_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Add SWA token as repository secret
        env:
          GH_TOKEN: ${{ secrets.REPO_SECRETS_TOKEN }}
          SWA_TOKEN: ${{ steps.get-swa-token.outputs.swa_token }}
        run: |
          gh secret set SWA_DEPLOYMENT_TOKEN --body "$SWA_TOKEN" --repo "${{ github.repository }}"

  deploy-portfolio:
    needs: deploy-infrastructure
    uses: ./.github/workflows/deploy-site.yml
    secrets:
      SWA_DEPLOYMENT_TOKEN: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
