name: Deploy and Connect Static Web App

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'iac/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ vars.AZURE_REGION }}
          template: ./iac/main.bicep
          parameters: >
            location=${{ vars.AZURE_REGION }}
            resourceGroupName=${{ vars.AZURE_RESOURCE_GROUP }}
            swaName=${{ vars.AZURE_SWA_NAME }}

      - name: Connect Static Web App to GitHub Repo
        run: |
          az staticwebapp connect \
            --name ${{ vars.AZURE_SWA_NAME }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --source "https://github.com/${{ github.repository }}" \
            --branch main \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --app-location "/" \
            --api-location "api" \
            --output-location "build"
