#########################################################################################
##  DEPLOY PORTFOLIO SITE
#########################################################################################
name: Deploy Portfolio Site

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  # Called by other workflows with required SWA deployment token
  workflow_call:
    secrets:
      SWA_DEPLOYMENT_TOKEN:
        required: true
  # Automatic trigger on push to main branch for non-IAC or workflow changes
  push:
    branches:
      - main
    paths-ignore:
      - 'iac/**'
      - '.github/**'
  # Automatic trigger on pull request events to main branch for non-IAC or workflow changes
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - 'iac/**'
      - '.github/**'

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
# Prevents multiple parallel runs of the workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  # Builds and deploys the portfolio site to Azure Static Web Apps
  build_and_deploy_job:
    if: ${{ !(github.event_name == 'pull_request' && github.event.action == 'closed') }}
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # The Azure SWA Deploy action automatically detects if this is a PR or push to main
      # For PRs: Creates/updates a preview environment with a unique URL
      # For push to main: Deploys to the production environment
      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: 'api' # Api source code path - optional
          output_location: 'dist/portfolio/browser' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  # Tears down the preview environment after the pull request is closed
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close pull request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          action: 'close'
          app_location: '/'
