name: Deploy and Connect Static Web App

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'iac/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ vars.AZURE_REGION }}
          template: ./iac/main.bicep
          parameters: >
            location=${{ vars.AZURE_REGION }}
            resourceGroupName=${{ vars.AZURE_RESOURCE_GROUP }}
            swaName=${{ vars.AZURE_SWA_NAME }}
            repoUrl=${{ github.server_url }}/${{ github.repository }}
            repoBranch=${{ github.ref_name }}

      - name: Get SWA deployment token
        id: get-swa-token
        run: |
          TOKEN=$(az staticwebapp secrets list \
            --name ${{ vars.AZURE_SWA_NAME }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --query "properties.apiKey" -o tsv)
          echo "::add-mask::$TOKEN"
          echo "swa_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Add SWA token as repository secret
        uses: actions/github-script@v7
        with:
          script: |
            const crypto = require('crypto');

            // Get the public key for the repository
            const { data: publicKeyInfo } = await github.rest.actions.getRepoPublicKey({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Encrypt the secret using the repository's public key
            const messageBytes = Buffer.from(${{ steps.get-swa-token.outputs.swa_token }});
            const keyBytes = Buffer.from(publicKeyInfo.key, 'base64');
            const encryptedBytes = crypto.publicEncrypt(
              {
                key: keyBytes,
                padding: crypto.constants.RSA_PKCS1_PADDING
              },
              messageBytes
            );

            // Create the secret
            await github.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: 'SWA_DEPLOYMENT_TOKEN',
              encrypted_value: encryptedBytes.toString('base64'),
              key_id: publicKeyInfo.key_id
            });
