name: Test Deploy to GitHub Pages

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  # Workflow will run on pull requests to the main branch.
  pull_request:
    types: [ closed ]
    branches:
      - main

#########################################################################################
##  PERMISSIONS
#########################################################################################
# Grant GITHUB_TOKEN the permissions required to make a Pages deployment.
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  build:
    name: Build and Test Portfolio Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run test-headless

      - name: Build
        run: npm run build

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/eslutz.github.io

  deploy_to_gh_pages:
    name: Deploy to Test Environment
    # This job will not run until build job finishes successfully.
    needs: build
    runs-on: ubuntu-latest
    # Deploy to the test-ericslutz.dev environment.
    environment:
      name: test-ericslutz.dev
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
